# Site settings
title: Daily Static Site News
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  <em>Daily Static Site News</em> is an example static site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kamon
github_username:  kamon

# Build settings
markdown: kramdown
